[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
formatter = {command='ruff',args=["format","-"]}
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

# if you choose `ruff` itself
[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp","tailwindcss-ls"]
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "tsx"
roots = [".git"]
language-servers = ["emmet-lsp","typescript-language-server","tailwindcss-ls"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
auto-format = true
