[[language]]
name = "python"
language-servers = [ "basedpyright", "ruff" ]
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
auto-format = true

[language-server.ruff]
command = "ruff-lsp"
[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language-server.basedpyright.config]
reportMissingTypeStubs = false
basedpyright.analysis.diagnosticSeverityOverrides.reportImplicitRelativeImport = false
basedpyright.analysis.diagnosticSeverityOverrides.reportUnknownMemberType = false
basedpyright.analysis.diagnosticSeverityOverrides.reportMissingTypeStubs = false

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp","tailwindcss-ls"]
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "tsx"
roots = [".git"]
language-servers = ["emmet-lsp","typescript-language-server","tailwindcss-ls"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
auto-format = true
