[manager]
show_hidden = true

[opener]
edit = [
	{ run = 'nvim "$@"', orphan = true },
]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
